services:
  - type: web
    name: rdi-service
    runtime: image
    image: ghcr.io/rudhachu/rdi:latest
    plan: starter
    region: frankfurt
    envVars:
      - key: RENDER_NAME
        sync: false
        required: true
      - key: RENDER_API
        sync: false
        required: true
      - key: SESSION_ID
        sync: false
        required: true
      - key: PREFIX
        sync: false
      - key: SUDO
        sync: false
      - key: MODE
        value: "private"
      - key: PORT
        value: "3000"
